### ISSUE TITLE
Getting script error when using with creatable with grouping

### ISSUE THREAD

**Issue by jainvizz** [jacobworrel/react-windowed-select#117]
I am using react-windowed-select along with React select creatable. 

Everything is working as expected if I am using flat options i.e. without any group, but if I am using grouped options and try to 
create a new option it breaks. 

Below is the code sand box link to replicate the issue.

https://codesandbox.io/s/youthful-aryabhata-7jgtdj

**Comment by kevingyang** [comment]
Fixed this issue in PR #130 @jainvizz
