### ISSUE TITLE
Menu Size

### ISSUE THREAD

**Issue by matthewkwong2** [jacobworrel/react-windowed-select#12]
Just a small thing:
The calculation of `menuHeight` is sometimes smaller than the actual height of the menu, adding an offset fix this problem.

i.e. In https://github.com/jacobworrel/react-windowed-select/blob/master/src/MenuList.js#L77
Change it to:
```js
const offset = 1; // offset = 1 is enough for me
const menuHeight = Math.min(maxHeight, totalHeight) + offset;
```

**Comment by jacobworrel** [comment]
@matthewkwong2 Thanks for logging this issue. Would you mind providing a [codesandbox](https://codesandbox.io) or code snippet that shows how you're using the library so I can reproduce this bug?

Thanks!

**Comment by jacobworrel** [comment]
@matthewkwong2 I'm unable to reproduce this based on the description you provided so I'm closing this issue. Will reopen if you provide a way for me to reproduce.
