### ISSUE TITLE
noOptionsMessage and loadingMessage are not passed proper params

### ISSUE THREAD

**Issue by peterjcoffman** [jacobworrel/react-windowed-select#19]
According to the [react-select documentation](https://react-select.com/props), noOptionsMessage and loadingMessage must be passed strings. Utils.js calls these functions without the required arguments, which will break if the messages use the strings they expect to be passed.

A workaround is to simply return an empty string if these functions are called with no arguments. This does not seem to affect the displayed message.

**Comment by jacobworrel** [comment]
Nice catch! Fixed in https://github.com/jacobworrel/react-windowed-select/pull/21
