### ISSUE TITLE
Grouped Options

### ISSUE THREAD

**Issue by Landoooooo** [jacobworrel/react-windowed-select#20]
Hey I've recently started using your npm package and first off it's amazing; it really speed up everything, so thank you. However there's an issue I'm facing with Grouping and I understand that you flattened them out for a reason, but is there a way for me implement them in same way react-select does?

**Comment by jacobworrel** [comment]
Not that I'm aware of. I think I flattened the group options originally bc `react-window` couldn't handle nested children, although I could be wrong.

If you have a better solution, I'd be happy to accept a PR! Closing this issue for now.
