### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by MasatsuguAida** [jacobworrel/react-windowed-select#44]
When open https://codesandbox.io/s/n592j4l13m and react-windowed-select update to 2.0.4,
Invariant Violation occurs.
Firefox 83.0

**Comment by jacobworrel** [comment]
Hi @MasatsuguAida - I'm not able to reproduce this issue.

**Comment by MasatsuguAida** [comment]
![1](https://user-images.githubusercontent.com/2852545/101434571-24a5a580-394e-11eb-9513-e292de9e8e7c.png)

Click Select...

![2](https://user-images.githubusercontent.com/2852545/101434581-2a02f000-394e-11eb-8f59-8775a119d26d.png)

Firefox 83.0 (64 bit)

**Comment by jacobworrel** [comment]
What am I missing?

<img width="1536" alt="Screen Shot 2020-12-07 at 7 16 01 PM" src="https://user-images.githubusercontent.com/13580141/101435169-b49d0e00-38c0-11eb-9694-aede0cfec9bb.png">

**Comment by MasatsuguAida** [comment]
Sorry, I'm using Windows 10.

**Comment by jacobworrel** [comment]
@MasatsuguAida Does this same error happen with the regular `react-select` `Select` component?

**Comment by MasatsuguAida** [comment]
No error happen with the regular react-select Select component.

https://codesandbox.io/s/react-windowed-select-forked-4r2z6

**Comment by jacobworrel** [comment]
Not sure how to fix this since I'm unable to reproduce this issue on my mac, but I would gladly accept a PR if you're able to find out a fix @MasatsuguAida.

**Comment by jacobworrel** [comment]
patch version 2.0.5 published to npm
