### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by athageir** [jacobworrel/react-windowed-select#47]
Hi! 
I noticed that the license in the package.json (`"license":"ISC"`) is different from the license in the LICENSE file (MIT). This causes tools like https://www.npmjs.com/package/licensecheck to behave unexpectedly. Could one of those licenses be chosen to be used in both places?

**Comment by zlargon** [comment]
Many companies have license policies to open source libraries. Hope the PR #48 can be approved and merged soon.
Thanks

**Comment by jacobworrel** [comment]
https://github.com/jacobworrel/react-windowed-select/pull/48 merged
