### ISSUE TITLE
Peer dep - react 17

### ISSUE THREAD

**Issue by Edsonzhu** [jacobworrel/react-windowed-select#49]
Hi, thanks for the package!

I'm getting a warning about peer dependencies when I npm i/npm ls react. Can we get an update on the react peer dep?

```npm ERR! peer dep missing: react@^16.8.0, required by react-windowed-select@2.0.5```

Thanks in Advance

**Comment by jacobworrel** [comment]
Done! React 17 works with react-windowed-select@4.0.0
