### ISSUE TITLE
Dynamic heights bugged when searching

### ISSUE THREAD

**Issue by amy-lei** [jacobworrel/react-windowed-select#51]
The options look great on initial load, but when I start searching, it gets a little weird. The example below is from [the codesandbox](https://codesandbox.io/s/laughing-mclaren-hzxqd?file=/src/App.js) linked in #31 .
![bug](https://user-images.githubusercontent.com/42757189/106532518-52c2e400-64be-11eb-891f-f87e733a1854.gif)

On my own branch, I found a workaround by taking `setMeasuredHeight` out of the `if` block, but it's at the cost of more rerenders. 
https://github.com/jacobworrel/react-windowed-select/blob/1f6c52bb3d7e0528af2b53a2eb2e94564ea4585b/src/MenuList.js#L158-L162

**Comment by jacobworrel** [comment]
@amy-lei Thanks for opening an issue! Would you be interested in submitting a PR - I think your workaround is fine unless there's a noticeable performance lag.

**Comment by amy-lei** [comment]
@jacobworrel Just submitted! I'm not sure if there's any tests I could've added.

**Comment by jacobworrel** [comment]
Thanks - will try to get this reviewed and merged as soon as I can.

**Comment by jacobworrel** [comment]
@amy-lei This is much better, but the option height is still not calculated correctly when searching for an option with a larger height (see attached screenshot). To reproduce, you can search for "Lorem" in the "long label text" story.  Would you be interested in taking a look at this?

<img width="1310" alt="Screen Shot 2021-02-12 at 2 40 54 PM" src="https://user-images.githubusercontent.com/13580141/107830253-5406d300-6d40-11eb-9932-34a70858306f.png">

**Comment by amy-lei** [comment]
Hmm I can try to look into this too.

**Comment by jacobworrel** [comment]
Thanks @amy-lei ! Let me know if you have any questions.
