### ISSUE TITLE
option height not calculated correctly when searching for option with dynamic height

### ISSUE THREAD

**Issue by jacobworrel** [jacobworrel/react-windowed-select#56]
@amy-lei This is much better, but the option height is still not calculated correctly when searching for an option with a larger height (see attached screenshot). To reproduce, you can search for "Lorem" in the "long label text" story.  Would you be interested in taking a look at this?

<img width="1310" alt="Screen Shot 2021-02-12 at 2 40 54 PM" src="https://user-images.githubusercontent.com/13580141/107830253-5406d300-6d40-11eb-9932-34a70858306f.png">

_Originally posted by @jacobworrel in https://github.com/jacobworrel/react-windowed-select/issues/51#issuecomment-778495849_

**Comment by gege83** [comment]
created a possible fix as a pull request (#58) I couldn't figure out how to test the change :(

**Comment by jacobworrel** [comment]
released in 3.1.2
