### ISSUE TITLE
react-windowed transfer component 

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [jacobworrel/react-windowed-select#69]
Hi,

Thank-you for this great component.  Can you please suggest if there is any transfer component developed with react-windowed integrated in it

Kind Regards,
Aditya

**Comment by jacobworrel** [comment]
Hi - Not sure what you mean. What's a "transfer component"? Can you please elaborate?

**Comment by aditya-padhi-kbl** [comment]
Sure.  It is something similar to :- https://ant.design/components/transfer/
There are 2 sections:-
The left selection component is known as source & the right selection is known as target.
We can select multiple items either from from source & target & the selected items can be moved by clicking on the direction button.

**Comment by jacobworrel** [comment]
@aditya-padhi-kbl I think this is outside of the scope of this project since this feature is not supported by the original `react-select` component.
