### ISSUE TITLE
upgrade react-select to version ^5

### ISSUE THREAD

**Issue by dmshvetsov** [jacobworrel/react-windowed-select#82]
hi, thanks for this package 🙌 

Do you have plans/intention for updating `react-select` dep from v4 to v5?

**Comment by jacobworrel** [comment]
Thanks @dmshvetsov ! I'll try to get around to this when I have some time but I've been busy so I can't promise anything. I would gladly accept a PR though if you feel up for it!

**Comment by dmshvetsov** [comment]
awesome. Same for me :) I would love to send a PR if I will find time.

**Comment by jacobworrel** [comment]
published in 5.0.0
