### ISSUE TITLE
Support for react 18

### ISSUE THREAD

**Issue by buzzwin** [jacobworrel/react-windowed-select#95]
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@1.0.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-windowed-select@5.0.0

Getting this error , any plans on testing with React 18 and upgrading ?

**Comment by jacobworrel** [comment]
@buzzwin This should be as straightforward as updating the peerDependencies in package.json to include react 18:

```
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
```

Would you be interested in making a PR?

**Comment by dg-robinson** [comment]
@jacobworrel just wondering if you've been able to review this PR yet?
